trigger:
  batch: true
  branches:
    include:
      - "*"

parameters:
  - name: acrTaskBranches
    default: '[ "main", "response" ]'
    type: string
  - name: salt
    default: ""
  - name: useWorkspace
    default: false
    type: boolean

variables:
  - template: variables.yml
  - name: saltVar
    ${{ if eq(parameters.useWorkspace, true) }}:
      value: ${{ parameters.salt }}
    ${{ else }}:
      value: ""

pool:
  name: 'jasojohnson-mcaps'

jobs:
  - job: Terraform
    displayName: "Infrastructure Deployment"
    steps:
      - template: terraform.yml
        parameters:
          terraformVersion: $(terraformVersion)
          terraformPath: $(terraformPath)
          servicePrinciple: $(servicePrinciple)
          containerName: $(terraformContainerName)
          storageAccountName: $(terraformStorageAccountName)
          workspace: ${{ variables.saltVar }}
          useWorkspace: ${{ parameters.useWorkspace }}
          resourceGroupName: $(terraformResourceGroupName)
          env:
            TF_VAR_salt: ${{ variables.saltVar }}
            TF_VAR_acr_branches: ${{ parameters.acrTaskBranches }}

  - job: DeployPythonApp
    displayName: "Deploy Python Application"
    dependsOn: Terraform
    variables:
      python_web_app_name: $[ dependencies.Terraform.outputs['Terraform.python_web_app_name'] ]
      resource_group_name: $[ dependencies.Terraform.outputs['Terraform.resource_group_name'] ]
    steps:
      # Setup Python environment
      - task: UsePythonVersion@0
        displayName: "Set Python Version"
        inputs:
          versionSpec: '3.13'
          addToPath: true
      
      # Install Python dependencies
      - task: Bash@3
        displayName: "Install Python Dependencies"
        inputs:
          targetType: 'inline'
          script: |
            cd $(Build.SourcesDirectory)/app
            python -m venv antenv
            source antenv/bin/activate
            python -m pip install --upgrade pip
            pip install setuptools  
            pip install -r requirements.txt
          workingDirectory: '$(Build.SourcesDirectory)'
      
      - task: ArchiveFiles@2
        displayName: 'Archive Python Application'
        inputs:
          rootFolderOrFile: '$(Build.SourcesDirectory)/app'
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          replaceExistingArchive: true

      - task: AzureWebApp@1
        displayName: 'Deploy Azure Web App : $(python_web_app_name)'
        inputs:
          azureSubscription: $(servicePrinciple)
          appName: $(python_web_app_name)
          package: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip